[package]
name = "orml-gradually-update"
description = "Provides way to adjust numeric parameter gradually over a period of time."
repository = "https://github.com/open-web3-stack/open-runtime-module-library/tree/master/gradually-update"
license = "Apache-2.0"
version = "0.1.3-dev"
authors = ["Laminar Developers <hello@laminar.one>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch",default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch",default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch",default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch",default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch",default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch",default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"sp-io/std",
	"sp-std/std",
	"sp-core/std",
	"sp-runtime/std",
]
